language: python
python:
  - 2.7
sudo: false
cache:
  directories:
  - $HOME/.pylint.d
  - eggs
matrix:
  fast_finish: true
install:
  - python bootstrap.py -c buildout.cfg
  - bin/buildout annotate
  - bin/buildout -N -q
# command to run tests
script:
  - bin/code-analysis
  - bin/test
  - pylint --py3k --disable=no-absolute-import collective/ploneqrcode
after_failure:
  - bin/buildout annotate
