language: python
python:
  - 2.7
sudo: false
cache:
  directories:
  - $HOME/.pylint.d
  - eggs
env:
    matrix:
      - PLONE_VERSION=4.3
matrix:
  fast_finish: true
before_install:
  # FIXME: I have no idea how and why six==1.11.0 is being installed
  - pip uninstall -y six
install:
  - python bootstrap.py -c buildout.cfg
  - bin/buildout annotate
  - bin/buildout -N -q
# command to run tests
script:
  - bin/code-analysis
  - bin/test
  - pylint --py3k --disable=no-absolute-import collective/ploneqrcode || true
after_failure:
  - bin/buildout annotate
